language: python

python:
    - "3.6"

install:
    - pip install -r requirements.txt

script:
    - pytest


before_deploy:
    - cd doc; bash makedoc.sh
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: doc/html
    verbose: true
    on:
        branch: master
